Table livre {
	id integer [ pk, increment, not null, unique ]
	libelle varchar
}

Table auteur {
	id integer [ pk, increment, not null, unique ]
	nom varchar
	prenom varchar
}

Table livre_auteurs {
	id integer [ pk, increment, not null, unique ]
	fk_livre integer
	fk_auteur integer
}

Table emprunt {
	id integer [ pk, increment, not null, unique ]
	date_emprunt date
	emprunteur integer
	date_restitution integer
	statut_emprunt varchar
}

Table emprunteur {
	id integer [ pk, increment, not null, unique ]
	nom varchar
	prenom varchar
}

Table livres_empruntes {
	id integer [ pk, increment, not null, unique ]
	fk_livre integer
	fk_emprunt integer
}

Ref fk_livre_auteurs_fk_livre_livre {
	livre_auteurs.fk_livre - livre.id [ delete: no action, update: no action ]
}

Ref fk_livre_auteurs_fk_auteur_auteur {
	livre_auteurs.fk_auteur - auteur.id [ delete: no action, update: no action ]
}

Ref fk_emprunt_emprunteur_emprunteur {
	emprunt.emprunteur - emprunteur.id [ delete: no action, update: no action ]
}

Ref fk_livres_empruntes_fk_emprunt_emprunt {
	livres_empruntes.fk_emprunt - emprunt.id [ delete: no action, update: no action ]
}

Ref fk_livres_empruntes_fk_livre_livre {
	livres_empruntes.fk_livre - livre.id [ delete: no action, update: no action ]
}
